# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/#sample-configuration for more details
#
# Steps for config yaml file

version: 2.0 #Start with Circle CI version.
jobs:
  build:

    docker:
    - image: circleci/ruby:2.4.2-jessie-node # ...with this image as the primary container; this is where all `steps` will run
            environment: # environment variables for primary container
              BUNDLE_JOBS: 1
              BUNDLE_RETRY: 1
              BUNDLE_PATH: vendor/bundle
              PGHOST: 127.0.0.1
              PGUSER: circleci-demo-ruby
              RAILS_ENV: test

      steps: # a collection of executable commands
        - checkout # special step to check out source code to working directory

        # Which version of bundler?
        - run:
            name: Which bundler?
            command: bundle -v

        # Restore bundle cache
        - restore_cache:
            keys:
              - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
              - rails-demo-bundle-v2-

        - run:
            name: Bundle Install
            command: bundle check || bundle install

        # Store bundle cache
        - save_cache:
            key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            paths:
              - vendor/bundle
#
#   EJEMPLO EJECUTOR
#        - run:
#            name: Run rspec in parallel
#            command: |
#              bundle exec rspec --profile 10 \
#                                --format RspecJunitFormatter \
#                                --out test_results/rspec.xml \
#                                --format progress \
#                                $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)



        workflows:
          version: 2
          build_and_test:
            jobs:
              - build